<?xml version="1.0"?>
<!-- Updated 2026-10-07: conditional ROS1/ROS2 dependencies. -->
<package format="3">
  <name>dynamixel_sdk_interface</name>
  <version>0.0.0</version>
  <description>ROS1/ROS2 DYNAMIXEL Protocol 2.0 interface and bus scanner.</description>
  <maintainer email="sungjae_min@kaist.ac.kr">Sungjae Min</maintainer>
  <license>GPL-3.0</license>
  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>
  <depend>lib_functions</depend>
  <depend>dynamixel_sdk</depend>
  <depend condition="$ROS_VERSION == 1">roscpp</depend>
  <depend condition="$ROS_VERSION == 2">rclcpp</depend>
  <exec_depend condition="$ROS_VERSION == 1">roslaunch</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">launch</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">launch_ros</exec_depend>
  <export>
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>
</package>
