#ifndef __DYNAMIXEL_XX_ADDRESSES_HPP__
#define __DYNAMIXEL_XX_ADDRESSES_HPP__

// ROM Area
#define ADDR_XX_MODEL_NUMBER                0
#define ADDR_XX_MODEL_INFORMATION           2
#define ADDR_XX_FIRMWARE_VERSION            6
#define ADDR_XX_ID                          7
#define ADDR_XX_BAUD_RATE                   8
#define ADDR_XX_RETURN_DELAY_TIME           9
#define ADDR_XX_DRIVE_MODE                  10
#define ADDR_XX_OPERATING_MODE              11
#define ADDR_XX_SECONDARY_ID                12
#define ADDR_XX_PROTOCOL_TYPE               13
#define ADDR_XX_HOMING_OFFSET               20
#define ADDR_XX_MOVING_THRESHOLD            24
#define ADDR_XX_TEMPERATURE_LIMIT           31
#define ADDR_XX_MAX_VOLTAGE_LIMIT           32
#define ADDR_XX_MIN_VOLTAGE_LIMIT           34
#define ADDR_XX_PWM_LIMIT                   36
#define ADDR_XX_CURRENT_LIMIT               38
#define ADDR_XX_ACCELERATION_LIMIT          40
#define ADDR_XX_VELOCITY_LIMIT              44
#define ADDR_XX_MAX_POSITION_LIMIT          48
#define ADDR_XX_MIN_POSITION_LIMIT          52
#define ADDR_XX_STARTUP_CONFIGURATION       60
#define ADDR_XX_PWM_SLOPE                   62
#define ADDR_XX_SHUTDOWN                    63

#define SIZE_XX_MODEL_NUMBER                2
#define SIZE_XX_MODEL_INFORMATION           4
#define SIZE_XX_FIRMWARE_VERSION            1
#define SIZE_XX_ID                          1
#define SIZE_XX_BAUD_RATE                   1
#define SIZE_XX_RETURN_DELAY_TIME           1
#define SIZE_XX_DRIVE_MODE                  1
#define SIZE_XX_OPERATING_MODE              1
#define SIZE_XX_SECONDARY_ID                1
#define SIZE_XX_PROTOCOL_TYPE               1
#define SIZE_XX_HOMING_OFFSET               4
#define SIZE_XX_MOVING_THRESHOLD            4
#define SIZE_XX_TEMPERATURE_LIMIT           1
#define SIZE_XX_MAX_VOLTAGE_LIMIT           2
#define SIZE_XX_MIN_VOLTAGE_LIMIT           2
#define SIZE_XX_PWM_LIMIT                   2
#define SIZE_XX_CURRENT_LIMIT               2
#define SIZE_XX_ACCELERATION_LIMIT          4
#define SIZE_XX_VELOCITY_LIMIT              4
#define SIZE_XX_MAX_POSITION_LIMIT          4
#define SIZE_XX_MIN_POSITION_LIMIT          4
#define SIZE_XX_STARTUP_CONFIGURATION       1
#define SIZE_XX_PWM_SLOPE                   1
#define SIZE_XX_SHUTDOWN                    1

// RAM Area
#define ADDR_XX_TORQUE_ENABLE               64
#define ADDR_XX_LED                         65
#define ADDR_XX_STATUS_RETURN_LEVEL         68
#define ADDR_XX_REGISTERED_INSTRUCTION      69
#define ADDR_XX_HARDWARE_ERROR_STATUS       70
#define ADDR_XX_VELOCITY_I_GAIN             76
#define ADDR_XX_VELOCITY_P_GAIN             78
#define ADDR_XX_POSITION_D_GAIN             80
#define ADDR_XX_POSITION_I_GAIN             82
#define ADDR_XX_POSITION_P_GAIN             84
#define ADDR_XX_FEEDFORWARD_2ND_GAIN        88
#define ADDR_XX_FEEDFORWARD_1ST_GAIN        90
#define ADDR_XX_BUS_WATCHDOG                98
#define ADDR_XX_GOAL_PWM                    100
#define ADDR_XX_GOAL_CURRENT                102
#define ADDR_XX_GOAL_VELOCITY               104
#define ADDR_XX_PROFILE_ACCELERATION        108
#define ADDR_XX_PROFILE_VELOCITY            112
#define ADDR_XX_GOAL_POSITION               116
#define ADDR_XX_REALTIME_TICK               120
#define ADDR_XX_MOVING                      122
#define ADDR_XX_MOVING_STATUS               123
#define ADDR_XX_PRESENT_PWM                 124
#define ADDR_XX_PRESENT_CURRENT             126
#define ADDR_XX_PRESENT_VELOCITY            128
#define ADDR_XX_PRESENT_POSITION            132
#define ADDR_XX_VELOCITY_TRAJECTORY         136
#define ADDR_XX_POSITION_TRAJECTORY         140
#define ADDR_XX_PRESENT_INPUT_VOLTAGE       144
#define ADDR_XX_PRESENT_TEMPERATURE         146
#define ADDR_XX_BACKUP_READY                147

#define SIZE_XX_TORQUE_ENABLE               1
#define SIZE_XX_LED                         1
#define SIZE_XX_STATUS_RETURN_LEVEL         1
#define SIZE_XX_REGISTERED_INSTRUCTION      1
#define SIZE_XX_HARDWARE_ERROR_STATUS       1
#define SIZE_XX_VELOCITY_I_GAIN             2
#define SIZE_XX_VELOCITY_P_GAIN             2
#define SIZE_XX_POSITION_D_GAIN             2
#define SIZE_XX_POSITION_I_GAIN             2
#define SIZE_XX_POSITION_P_GAIN             2
#define SIZE_XX_FEEDFORWARD_2ND_GAIN        2
#define SIZE_XX_FEEDFORWARD_1ST_GAIN        2
#define SIZE_XX_BUS_WATCHDOG                1
#define SIZE_XX_GOAL_PWM                    2
#define SIZE_XX_GOAL_CURRENT                2
#define SIZE_XX_GOAL_VELOCITY               4
#define SIZE_XX_PROFILE_ACCELERATION        4
#define SIZE_XX_PROFILE_VELOCITY            4
#define SIZE_XX_GOAL_POSITION               4
#define SIZE_XX_REALTIME_TICK               2
#define SIZE_XX_MOVING                      1
#define SIZE_XX_MOVING_STATUS               1
#define SIZE_XX_PRESENT_PWM                 2
#define SIZE_XX_PRESENT_CURRENT             2
#define SIZE_XX_PRESENT_VELOCITY            4
#define SIZE_XX_PRESENT_POSITION            4
#define SIZE_XX_VELOCITY_TRAJECTORY         4
#define SIZE_XX_POSITION_TRAJECTORY         4
#define SIZE_XX_PRESENT_INPUT_VOLTAGE       2
#define SIZE_XX_PRESENT_TEMPERATURE         1
#define SIZE_XX_BACKUP_READY                1

#endif
